### ISSUE TITLE
JSON formatting issue on rage

### ISSUE THREAD

**Issue by johnch18** [pcattori/pokemon#19]
See title

**Comment by pcattori** [comment]
If you are referring to [`rage` move in the moves list](https://github.com/pcattori/pokemon/blob/0984a0418f107d09fa82596ea32e8b24318b7ae5/pokemon/data/moves.json#L101), Github doesn't syntax highlight it since its a long line, but copy/pasting that line into JSON validators/formatters online shows that it is valid JSON.

(feel free to reopen if I misinterpreted)
